all: question-1 question-4 question-5 question-6 question-7

question-1:
        gcc -g question-1.c -o question-1
question-4:
        gcc -g question-4.c -o question-4
question-5:
        gcc -g question-5.c -o question-5
question-6:
        gcc -g question-6.c -o question-6
question-7:
        gcc -g question-7.c -o question-7