import pynput

up = pynput.keyboard.Key.up
down = pynput.keyboard.Key.down
left = pynput.keyboard.Key.left
right = pynput.keyboard.Key.right

support_airburstRocketLauncher  = [down, up, up, left, right]
support_antiMaterialRifle       = [down, left, right, up, down]
support_arcThrower              = [down, right, down, up, left, left]
support_autocannon              = [down, left, down, up, up, right]
suuport_commando                = [down, left, up, down, right]
support_deEscalator             = [down, right, up, left, right]
support_defoliationTool         = [down, left, right, right, down]
support_epoch                   = [down, left, up, left, right]
support_expendableAntiTank      = [down, down, left, up, right]
support_expendableNapalm        = [down, down, left, up, left]
support_flamethrower            = [down, left, up, down, up]
support_grenadeLauncher         = [down, left, up, left, down]
support_heavyMachineGun         = [down, left, up, down, down]
support_laserCannon             = [down, left, up, left, down]
support_machineGun              = [down, left, down, up, right]
support_maxigun                 = [down, left, right, down, up, up]
support_oneTrueFlag             = [down, left, right, right, up]
support_quasarCannon            = [down, down, up, left, right]
support_railgun                 = [down, right, down, up, left, right]
support_recoillessRifle         = [down, left, right, right, left]
support_soloSilo                = [down, up, right, down, down]
support_spear                   = [down, down, up, down, down]
supprot_spearGun                = [down, right, down, left, up, right]
support_stalwart                = [down, left, down, up, up, left]
support_sterilizer              = [down, left, up, down, left]
support_waspLauncher            = [down, down, up, down, right]

backpack_ballisticShield    = [down, left, down, down, up, left]
backpack_c4Pack             = [down, right, up, up, right, up]
backpack_directionalShield  = [down, up, left, right, up, up]
backpack_guardDog           = [down, up, left, up, right, down]
backpack_guardDogDogBreath  = [down, up, left, up, right, up]
backpack_guardDogHotDog     = [down, up, left, up, left, left]
backpack_guardDogK9         = [down, up, left, up, right, left]
backpack_guardDogRover      = [down, up, left, up, right, right]
backpack_hoverPack          = [down, up, up, down, left, right]
backpack_jumpPack           = [down, up, up, down, up]
backpack_personalShield     = [down, up, left, right, left, right]
backpack_portableHellbomb   = [down, right, up, up, up]
backpack_supplyPack         = [down, left, down, up, up, down]
backpack_warpPack           = [down, left, right, down, left, right]

defensive_antiTankEmplacement   = [down, up, left, right, right, right]
defensive_grenadierBattlement   = [down, right, down, left, right]
defensive_hmgEmplacment         = [down, up, left, right, right, left]
defensive_shieldGenerator       = [down, down, left, right, left, right]

sentry_autocannon   = [down, up, right, up, left, up]
sentry_emsMortar    = [down, up, right, down, right]
sentry_flame        = [down, up, right, down, up, up]
sentry_gatling      = [down, up, right, left]
sentry_laser        = [down, up, right, down, up, right]
sentry_machineGun   = [down, up, right, right, up]
sentry_mortar       = [down, up, right, right, down]
sentry_rocket       = [down, up, right, right, left]
sentry_teslaTower   = [down, up, right, up, left, down]

mine_antiPersonnel  = [down, left, up, right]
mine_antiTank       = [down, left, up, up]
mine_gas            = [down, left, left, right]
mine_incindiary     = [down, left, left, down]

orbital_120mmBarrage        = [right, right, down, left, right, down]
orbital_380mmBarrage        = [right, down, up, up, left, down, down]
orbital_airburstStrike      = [right, right, right]
orbital_emsStrike           = [right, right, left, down]
orbital_gasStrike           = [right, right, down, right]
orbital_gatlingBarrage      = [right, down, left, up, up]
orbital_laser               = [right, down, up, right, down]
orbital_napalm              = [right, right, down, left, right, up]
orbital_precisionStrike     = [right, right, up]
orbital_railcannonStrike    = [right, up, down, down, right]
orbital_smokeStrike         = [right, right, down, up]
orbital_walkingBarrage      = [right, down, right, down, right, down]

eagle_110mmRocketPods   = [up, down, up, left]
eagle_500kgBomb         = [up, right, down, down, down]
eagle_airstrike         = [up, right, down, right]
eagle_clusterBomb       = [up, right, down, down, right]
eagle_napalmAirstrike   = [up, right, down, up]
eagle_smokeStrike       = [up, right, up, down]
eagle_strafingRun       = [up, right, right]

vehicle_emancipatorExosuit = [left, down, right, up, left, down, up]
vehicle_fastReconVehicle = [left, down, right, down, right, down, up]
vehicle_patriotExosuit     = [left, down, right, up, left, down, down]

mission_reinforce       = [up, down, right, left, up]
mission_resupply        = [down, down, up, right]

none = []