import pynput

up = pynput.keyboard.Key.up
down = pynput.keyboard.Key.down
left = pynput.keyboard.Key.left
right = pynput.keyboard.Key.right

support_airburstRocketLauncher  = [down, up, up, left, right, "airburstRocketLauncher"]
support_antiMaterialRifle       = [down, left, right, up, down, "antiMaterialRifle"]
support_arcThrower              = [down, right, down, up, left, left, "arcThrower"]
support_autocannon              = [down, left, down, up, up, right, "autocannon"]
suuport_commando                = [down, left, up, down, right, "commando"]
support_deEscalator             = [down, right, up, left, right, "deEscalator"]
support_defoliationTool         = [down, left, right, right, down, "defoliationTool"]
support_epoch                   = [down, left, up, left, right, "epoch"]
support_expendableAntiTank      = [down, down, left, up, right, "expendableAntiTank"]
support_expendableNapalm        = [down, down, left, up, left, "expendableNapalm"]
support_flamethrower            = [down, left, up, down, up, "flamethrower"]
support_grenadeLauncher         = [down, left, up, left, down, "grenadeLauncher"]
support_heavyMachineGun         = [down, left, up, down, down, "heavyMachineGun"]
support_laserCannon             = [down, left, up, left, down, "laserCannon"]
support_machineGun              = [down, left, down, up, right, "machineGun"]
support_maxigun                 = [down, left, right, down, up, up, "maxigun"]
support_oneTrueFlag             = [down, left, right, right, up, "oneTrueFlag"]
support_quasarCannon            = [down, down, up, left, right, "quasarCannon"]
support_railgun                 = [down, right, down, up, left, right, "railgun"]
support_recoillessRifle         = [down, left, right, right, left, "recoillessRifle"]
support_soloSilo                = [down, up, right, down, down, "soloSilo"]
support_spear                   = [down, down, up, down, down, "spear"]
supprot_spearGun                = [down, right, down, left, up, right, "spearGun"]
support_stalwart                = [down, left, down, up, up, left, "stalwart"]
support_sterilizer              = [down, left, up, down, left, "sterilizer"]
support_waspLauncher            = [down, down, up, down, right, "waspLauncher"]

backpack_ballisticShield    = [down, left, down, down, up, left, "ballisticShield"]
backpack_c4Pack             = [down, right, up, up, right, up, "c4Pack"]
backpack_directionalShield  = [down, up, left, right, up, up, "directionalShield"]
backpack_guardDog           = [down, up, left, up, right, down, "guardDog"]
backpack_guardDogDogBreath  = [down, up, left, up, right, up, "guardDogDogBreath"]
backpack_guardDogHotDog     = [down, up, left, up, left, left, "guardDogHotDog"]
backpack_guardDogK9         = [down, up, left, up, right, left, "guardDogK9"]
backpack_guardDogRover      = [down, up, left, up, right, right, "guardDogRover"]
backpack_hoverPack          = [down, up, up, down, left, right, "hoverPack"]
backpack_jumpPack           = [down, up, up, down, up, "jumpPack"]
backpack_personalShield     = [down, up, left, right, left, right, "personalShield"]
backpack_portableHellbomb   = [down, right, up, up, up, "portableHellbomb"]
backpack_supplyPack         = [down, left, down, up, up, down, "supplyPack"]
backpack_warpPack           = [down, left, right, down, left, right, "warpPack"]

defensive_antiTankEmplacement   = [down, up, left, right, right, right, "antiTankEmplacement"]
defensive_grenadierBattlement   = [down, right, down, left, right, "grenadierBattlement"]
defensive_hmgEmplacment         = [down, up, left, right, right, left, "hmgEmplacment"]
defensive_shieldGenerator       = [down, down, left, right, left, right, "shieldGenerator"]

sentry_autocannon   = [down, up, right, up, left, up, "autocannon"]
sentry_emsMortar    = [down, up, right, down, right, "emsMortar"]
sentry_flame        = [down, up, right, down, up, up, "flame"]
sentry_gatling      = [down, up, right, left, "gatling"]
sentry_laser        = [down, up, right, down, up, right, "laser"]
sentry_machineGun   = [down, up, right, right, up, "machineGun"]
sentry_mortar       = [down, up, right, right, down, "mortar"]
sentry_rocket       = [down, up, right, right, left, "rocket"]
sentry_teslaTower   = [down, up, right, up, left, down, "teslaTower"]

mine_antiPersonnel  = [down, left, up, right, "antiPersonnel"]
mine_antiTank       = [down, left, up, up, "antiTank"]
mine_gas            = [down, left, left, right, "gas"]
mine_incindiary     = [down, left, left, down, "incindiary"]

orbital_120mmBarrage        = [right, right, down, left, right, down, "120mmBarrage"]
orbital_380mmBarrage        = [right, down, up, up, left, down, down, "380mmBarrage"]
orbital_airburstStrike      = [right, right, right, "airburstStrike"]
orbital_emsStrike           = [right, right, left, down, "emsStrike"]
orbital_gasStrike           = [right, right, down, right, "gasStrike"]
orbital_gatlingBarrage      = [right, down, left, up, up, "gatlingBarrage"]
orbital_laser               = [right, down, up, right, down, "laser"]
orbital_napalm              = [right, right, down, left, right, up, "napalm"]
orbital_precisionStrike     = [right, right, up, "precisionStrike"]
orbital_railcannonStrike    = [right, up, down, down, right, "railcannonStrike"]
orbital_smokeStrike         = [right, right, down, up, "smokeStrike"]
orbital_walkingBarrage      = [right, down, right, down, right, down, "walkingBarrage"]

eagle_110mmRocketPods   = [up, down, up, left, "110mmRocketPods"]
eagle_500kgBomb         = [up, right, down, down, down, "500kgBomb"]
eagle_airstrike         = [up, right, down, right, "airstrike"]
eagle_clusterBomb       = [up, right, down, down, right, "clusterBomb"]
eagle_napalmAirstrike   = [up, right, down, up, "napalmAirstrike"]
eagle_smokeStrike       = [up, right, up, down, "smokeStrike"]
eagle_strafingRun       = [up, right, right, "strafingRun"]

vehicle_emancipatorExosuit  = [left, down, right, up, left, down, up, "emancipatorExosuit"]
vehicle_fastReconVehicle    = [left, down, right, down, right, down, up, "fastReconVehicle"]
vehicle_patriotExosuit      = [left, down, right, up, left, down, down, "patriotExosuit"]

mission_reinforce       = [up, down, right, left, up, "reinforce"]
mission_resupply        = [down, down, up, right, "resupply"]


none = []