# Generated by Django 3.1.6 on 2022-06-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inn',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inn_npc', to='app.npc'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='sponsor_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest_org', to='app.orginization'),
        ),
    ]
