# Generated by Django 3.1.6 on 2022-06-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220609_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kingdom',
            name='level_corruption',
        ),
    ]
