# Generated by Django 3.1.6 on 2022-06-09 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_kingdom_level_corruption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Big_Bad',
            new_name='Big_Bad_model',
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='City_model',
        ),
        migrations.RenameModel(
            old_name='Dungeon',
            new_name='Dungeon_model',
        ),
        migrations.RenameModel(
            old_name='Fast_Travel_Route',
            new_name='Fast_Travel_Route_model',
        ),
        migrations.RenameModel(
            old_name='Inn',
            new_name='Inn_model',
        ),
        migrations.RenameModel(
            old_name='kingdom',
            new_name='Kingdom_model',
        ),
        migrations.RenameModel(
            old_name='Large_Threat',
            new_name='Large_Threat_model',
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='Location_model',
        ),
        migrations.RenameModel(
            old_name='NPC',
            new_name='NPC_model',
        ),
        migrations.RenameModel(
            old_name='Orginization',
            new_name='Orginization_model',
        ),
        migrations.RenameModel(
            old_name='Quest',
            new_name='Quest_model',
        ),
        migrations.RenameModel(
            old_name='Shop',
            new_name='Shop_model',
        ),
        migrations.RenameModel(
            old_name='Tavern',
            new_name='Tavern_model',
        ),
    ]
