# Generated by Django 3.1.6 on 2022-06-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220609_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest_model',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='fast_travel_route_model',
            name='name',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orginization_model',
            name='name',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
    ]
